$(document).ready(function(){
    $('.slider').slick({
        arrows:false,
        dots:true,
        adaptiveHeight:true,
        infinite:false,
        easing:'ease',
        centerMode:true,
    });
})